name: Pengweb
favicon: null
layout_spectrum: 0.2518
typography_spectrum: 0.52966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#ffda00'
    - '#4609d2'
    - '#00e200'
    - '#008e00'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
